[package]
name = "privacy_http_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "native-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
# Make this library compatible with C++
crate-type = ["cdylib"]

[features]
default = []
