[package]
name = "privacy_http_sdk"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.12", features = ["json", "native-tls"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1", features = ["full"] }
cxx = "1.0.135"
openai = "1.0.0-alpha.17"
rig-core = "0.5.0"

[build-dependencies]
cxx-build = "1.0.135"

[lib]
# Make this library compatible with C++
crate-type = ["cdylib"]

[features]
default = []
